# Colors & Variables
set -g @thm_g0 "#16161D"
set -g @thm_g1 "#1F1F28"
set -g @thm_g2 "#2A2A37"
set -g @thm_g3 "#363646"
set -g @thm_g4 "#44445D"
set -g @thm_accent "#9CABCA"
set -g @thm_accent2 "#e6c384"

# Status Bar General
set-option -gF status-style "bg=#{@thm_g0},fg=#{@thm_g4},none"
set-option -g status-left-length 150
set-option -g status-right-length 150
set-option -g status-interval 10
set-option -g status on
set-option -g status-position top

# Left Side (Session Name)
set-option -g status-left "#[fg=#{@thm_g0},bg=#{@thm_accent2},bold] #S #[fg=#{@thm_accent2},bg=#{@thm_g0},nobold]▌"

# Right Side (Battery Info & Clock)
set-option -g status-right "\
#{prefix_highlight} \
#[fg=#{@thm_accent},bg=#{@thm_g0}]#(~/.config/tmux/status.sh #{pane_tty}) \
#[fg=#{@thm_g2}]#[fg=#{@thm_accent},bg=#{@thm_g2}] #(~/.config/tmux/battery.sh) \
#[fg=#{@thm_accent},bg=#{@thm_g2}]▐#[fg=#{@thm_g0},bg=#{@thm_accent},bold] %a %d %H:%M "

# Window Status Format
set-option -g window-status-format "#[fg=#{@thm_g0},bg=#{@thm_g2}]▌#[fg=#{@thm_accent},bg=#{@thm_g2},nobold] #I:#W#F #[fg=#{@thm_g2},bg=#{@thm_g0}]▌"
set-option -g window-status-current-format "#[fg=#{@thm_g0},bg=#{@thm_accent}]▌#[fg=#{@thm_g0},bg=#{@thm_accent},bold] #I:#W#F #[fg=#{@thm_accent},bg=#{@thm_g0},nobold]▌"

# Window Styles
set-option -gF window-status-style "fg=#{@thm_accent},bg=#{@thm_g0},none"
set-option -gF window-status-last-style "fg=#{@thm_accent},bg=#{@thm_g0},bold"
set-option -gF window-status-activity-style "fg=#{@thm_accent},bg=#{@thm_g0},bold"
set-option -g window-status-separator ""

# Panes & UI
set-option -gF pane-border-style "fg=#{@thm_g3},bg=default"
set-option -gF pane-active-border-style "fg=#{@thm_accent},bg=default"
set-option -gF display-panes-colour "#{@thm_g3}"
set-option -gF display-panes-active-colour "#{@thm_accent}"

# Clock Mode
set-option -gF clock-mode-colour "#{@thm_accent}"
set-option -g clock-mode-style 24

# Messages
set-option -gF message-style "fg=#{@thm_accent},bg=#{@thm_g0}"
set-option -gF message-command-style "fg=#{@thm_accent},bg=#{@thm_g0}"

# Copy Mode
set-option -gF mode-style "bg=#{@thm_accent},fg=#{@thm_g4}"

# Prefix Highlight Plugin Support
set-option -g @prefix_highlight_show_copy_mode 'on'
set-option -gF @prefix_highlight_copy_mode_attr "fg=#{@thm_accent},bg=#{@thm_g0},bold"
set-option -gF @prefix_highlight_output_prefix "#[fg=#{@thm_g2}]#[bg=#{@thm_g0}]▐#[bg=#{@thm_g2}]#[fg=#{@thm_accent}]"
set-option -gF @prefix_highlight_output_suffix "#[fg=#{@thm_g2}]#[bg=#{@thm_g0}]▌"
