gui:
  tabWidth: 2
  showRootItemInFileTree: false
  showNumstatInFilesView: true
  showRandomTip: false
  statusPanelView: allBranchesLog
  expandFocusedSidePanel: true

git:
  overrideGpg: true
  allBranchesLogCmds:
    -  git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=oneline
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

