# Dotfiles

[[session]]
name = "dotfiles"
path = "~/dotfiles"
windows = [ "nvim" ]
startup_command = "nvim ."

[[window]]
name = "nvim"
startup_script = "cd .config/nvim; nvim ."

# Fema

[[session]]
name = "fema"
path = "~/dev/work/krbl/fema"
windows = [ "protocol", "tests" ]
startup_command = "tmux rename-window \"server\"; cd FemaServer; nvim ."

[[window]]
name = "protocol"
startup_script = "cd FemaProtocol; nvim ."

[[window]]
name = "tests"
startup_script = "cd FemaTests; nvim ."

# SSH

[[session]]
name = "ssh"
startup_command = "tmux rename-window \"polygon\"; clear"
windows = [ "mys", "ekb", "ml" ]

[[window]]
name = "mys"

[[window]]
name = "ekb"

[[window]]
name = "ml"

# Other

[[session]]
name = "go-refs"
path = "~/dev/third_party/go-references"

[[session]]
name = "misc"
path = "~"

[[session]]
name = "obsidian"
path = "~/obsidian/ae4"
startup_command = "nvim ."


[[session]]
name = "daily"
path = "~/daily"
startup_command = "daily"

# Tmp - creates new session with autoincrementing number

[[session]]
name = "tmp"
startup_command = "tmux rename-session \"tmp$(sesh list -t | grep 'tmp\\d' | wc -l | xargs)\"; clear"

# New creates new session and give you name it

[[session]]
name = "new"
startup_command = "tmux command-prompt -p 'New session name:' \"rename-session '%%'\"; clear"
