#! /bin/sh

# Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Bind workspace to monitors
monitor_count=$(xrandr --query | grep "\bconnected" --count)
case $monitor_count in
  1)
    bspc monitor -d 1 2 3 4 5 6
  ;;
  2)
    bspc monitor HDMI-1 -d 1 2 3
    bspc monitor eDP-1 -d 4 5 6
  ;;
esac

# Wallpaper
# feh --bg-tile ~/wallpapers/wide.png
feh --bg-fill ~/wallpapers/Pixel-city.png

# Windows setup
bspc config border_width         2
bspc config window_gap           7
bspc config normal_border_color  "#595959"
bspc config focused_border_color "#98BB6C"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

# Composer
picom --config ~/.config/picom/picom.conf  &

# Polybar
$HOME/.config/polybar/launch.sh
